[package]
name = "westwood"
version = "0.1.0"
edition = "2021"

[build-dependencies]
cc = "*"

[dependencies]
ariadne = { version = "0.5.0", features = ["concolor", "auto-color"] }
tree-sitter = "0.25.3"
tree-sitter-c = "0.23.4"
